### PR TITLE
Upgrade to ember 3.28

### PR DESCRIPTION
**Pull request by BnitoBzh**
Upgrade to the last ember LTS (3.28.x)
Update all dependencies
Glimmer component / ES6
Tests improvement

There are probably more things to do (like Typescript), but for now it's a good start.

This should be publish as a major version (drop support for older Ember versions than v3.24)

### CODE REVIEW

**Comment by BnitoBzh** [comment]
Hi there !

Is my PR can be merged ? With a new major version ?

**Comment by BnitoBzh** [comment]
@lstrrs can my pull request be merged ?
You could add me as maintainer if you have no time to get this addon up to date

**Comment by lstrrs** [comment]
Closing this PR in favor of https://github.com/lstrrs/ember-line-clamp/pull/82

**Comment by lstrrs** [comment]
Closing this PR in favor of https://github.com/lstrrs/ember-line-clamp/pull/82

**Pull request closed without merging**
